#!/usr/bin/env bash

# Exit When Any Command Fails
set -e

echo "-----------------------------"
echo "| Running Lint Checking |"
echo "-----------------------------"
sh -c "pnpm run lint"

echo "-----------------------------"
echo "| Running Type Checking |"
echo "-----------------------------"
sh -c "pnpm run typecheck"

echo "-----------------------------"
echo "| Running Build |"
echo "-----------------------------"
sh -c "pnpm run build"
