import '@/app/globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { themeClass } from './darkmode/utils';

const font = Poppins({
  weight: ['700', '600', '500', '400'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={themeClass()}>
      <body className={`${font.className} bg-gray-100 dark:bg-gray-900`}>
        {children}
      </body>
    </html>
  );
}
